Repository redBorder/redborder-serverspec-proxy, pull requests merged in 2024-06, with the labels that each got.

#18 check geoip
  spec/configuration/geoip_spec.rb
Labels: size/S, kind/bug

#21 add logstash test
  spec/services/logstash_spec.rb
Labels: kind/feature, size/M

#20 gemfile update
  Gemfile
Labels: bug, size/XS, kind/documentation
